package golem:template

interface api {
  record dialog-result {
    book: option<book>
  }

  record book {
    title: string,
    author: string,
    rating: u32
  }

  step: func(update: string) -> result<dialog-result, string>
}

world add-book-dialog {
  export api
}
